
name = "ai-research-assistant"
main = "src/index.js"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "CHAT_SESSIONS"
class_name = "ChatSession"
script_name = "ai-research-assistant"

[[migrations]]
tag = "v1"
new_classes = ["ChatSession"]
